name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./assets/github-contribution-grid-snake.svg
            ./assets/github-contribution-grid-snake-dark.svg?palette=github-dark
            ./assets/github-contribution-grid-snake.gif
            ./assets/github-contribution-grid-snake-dark.gif?palette=github-dark

      - name: Debug Outputs
        run: ls -la ./assets

      - name: Push to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Generate Contribution Snake'
          branch: main
